apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-k8s-deployment-$BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
      - name: sample-k8s-app-container
        image: vaibhav27/hello-world:$BUILD_NUMBER
        ports:
        - containerPort: 8080
