apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-svc
spec:
  selector:
    matchLabels:
      app: helloworld-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-svc
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: helloworld-svc
    

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
spec:
  rules:
  - host: mgmt.torq.trans.apps.ge.com
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld-svc
          servicePort: 80
