apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-k8s-deployment1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
      - name: sample-k8s-app-container
        image: registry.gear.ge.com/212587274/test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
