apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-k8s-deployment2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
      - name: sample-k8s-app-container
        image: 456624778202.dkr.ecr.us-east-1.amazonaws.com/genodejs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
